name: rpm-release
on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: Tag to push the sources to
        required: true
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag to push the sources to
        required: true
permissions:
  contents: write
# Spend CI time only on latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
jobs:
  create-sources:
    runs-on: ubuntu-24.04
    container:
      image: fedora:41
    steps:
      - name: install dependencies
        run: |
          dnf install -y git make rustc cargo jq fedora-packager rpmlint
      - uses: actions/checkout@v6
      # BUG: fixes permission in github actions container
      - name: set safe git directory
        run: |
          git config --system --add safe.directory "$PWD"
      - name: install build dependencies
        run: dnf builddep -y rpm/rust-note.spec
      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: build the rpm
        run: |
          make -C rpm sources SOURCE_DIR=./
      - name: upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: sources
          if-no-files-found: error
          path: |
            rpm/note-*.crate
            rpm/rust-note-*-vendor.tar.xz
  upload-to-release:
    runs-on: ubuntu-24.04
    needs: create-sources
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v7
        with:
          name: sources
      - name: upload to relase
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ inputs.tag }}
          WEBHOOK: ${{ secrets.COPR_WEBHOOK }}
        run: |
          find -type f
          gh release upload -R "$REPOSITORY" "$TAG" \
            note-*.crate \
            rust-note-*-vendor.tar.xz
          curl -X POST "$WEBHOOK/rust-note"
